./cplus-sandpiles 8 | pnmtopng images/8-center.ppm > images/8-center.png
./cplus-sandpiles 9 | pnmtopng images/9-center.ppm > images/9-center.png
./cplus-sandpiles 10 | pnmtopng images/10-center.ppm > images/10-center.png
./cplus-sandpiles 11 | pnmtopng images/11-center.ppm > images/11-center.png
./cplus-sandpiles 12 | pnmtopng images/12-center.ppm > images/12-center.png
./cplus-sandpiles 13 | pnmtopng images/13-center.ppm > images/13-center.png
./cplus-sandpiles 14 | pnmtopng images/14-center.ppm > images/14-center.png
./cplus-sandpiles 15 | pnmtopng images/15-center.ppm > images/15-center.png
./cplus-sandpiles 16 | pnmtopng images/16-center.ppm > images/16-center.png
./cplus-sandpiles 17 | pnmtopng images/17-center.ppm > images/17-center.png
./cplus-sandpiles 18 | pnmtopng images/18-center.ppm > images/18-center.png
./cplus-sandpiles 19 | pnmtopng images/19-center.ppm > images/19-center.png
./cplus-sandpiles 20 | pnmtopng images/20-center.ppm > images/20-center.png
